server:
  port: 8888

spring:  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Kelymelo/microservice-repo
          search-paths: fornecedor
       
          
             